server:
  port : 8081
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://mysql.default.svc.cluster.local:3306/product_db?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  transaction:
    default-timeout: 10
    rollback-on-commit-failure: true
