#!/bin/bash
echo "Running git pre-commit hook"
./gradlew ktlintCheck
ktlintCheckStatus=$?
# return 1 if check fails
if [[ $ktlintCheckStatus -ne 0 ]]; then
    echo "ktlint check failed. Please fix the issues before committing."
    exit 1
else
    exit 0
fi
