name: PR Check

on:
  pull_request:

jobs:
  build:
    name: Build Gradle Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew ktlintCheck
      - run: ./gradlew test
